import Sidebar from '@/components/Sidebar'
import '@/styles/globals.css'

export const metadata = {
  title: 'Amazon Web Scraper',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Sidebar */}
        <Sidebar />
        <main>
          {/* Header */}
          {children}
          
        </main>
        </body>
    </html>
  )
}
